### ISSUE TITLE
include assets

### ISSUE THREAD

**Issue by stevetoro** [VladislavKiel/prj-rev-bwfs-dasmoto#3]
https://github.com/VladislavKiel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L18

Include your website's assets (in this case images) in your project and provide a relative file path to them in your `img` tags. 

It's always better to provide static assets up front instead of depending on external URLs that could fail or otherwise become unavailable.

**Comment by VladislavKiel** [comment]
done
