### ISSUE TITLE
pricing

### ISSUE THREAD

**Issue by stevetoro** [VladislavKiel/prj-rev-bwfs-dasmoto#5]
https://github.com/VladislavKiel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L20

Nice job using a proper inline tag like `strong` to write your price information 👍 

Give each of these tags the same _class_. Use classes to group multiple elements and use IDs to identify individual unique elements.

Using the same, but descriptive, class allows you to easily select all of the `strong` tags related to pricing, apply styles to them in your stylesheet, and will prevent bugs in the future.

**Comment by VladislavKiel** [comment]
done, thanks
